const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Create Schema
const PlayerSchema = new Schema({
    slug: String,
    name: String,
    positions: String,
    age: Number,
    year: Number,
    team: String,
    games_played: Number,
    games_started: Number,
    minutes_played: Number,
    games_started: Number,
    minutes_played: Number,
    made_field_goals: Number,
    attempted_field_goals: Number,
    made_three_point_field_goals: Number,
    attempted_three_point_field_goals: Number,
    made_free_throws: Number,
    attempted_free_throws: Number,
    offensive_rebounds: Number,
    defensive_rebounds: Number,
    assists: Number,
    steals: Number,
    blocks: Number,
    turnovers: Number,
    personal_fouls: Number,
    assist_percentage: Number,
    block_percentage: Number,
    box_plus_minus: Number,
    defensive_box_plus_minus: Number,
    defensive_rebound_percentage: Number,
    defensive_win_shares: Number,
    free_throw_attempt_rate: Number,
    offensive_box_plus_minus: Number,
    offensive_rebound_percentage: Number,
    offensive_win_shares: Number,
    layer_efficiency_rating: Number,
    steal_percentage: Number,
    three_point_attempt_rate: Number,
    total_rebound_percentage: Number,
    true_shooting_percentage: Number,
    turnover_percentage: Number,
    usage_percentage: Number,
    value_over_replacement_player: Number,
    win_shares: Number,
    win_shares_per_48_minutes: Number,
    height: Number,
    weight: Number,
    'per game FG': Number,
    'per game FGA': Number,
    'per game 3P': Number,
    'per game 3PA': Number,
    'per game 2P': Number,
    'per game 2PA': Number,
    'per game FT': Number,
    'per game FTA': Number,
    'per game ORB': Number,
    'per game DRB': Number,
    'per game TRB': Number,
    'per game AST': Number,
    'per game STL': Number,
    'per game BLK': Number,
    'per game TOV': Number,
    'per game PF': Number,
    'per game PTS': Number,
    'At Rim FG': Number,
    'At Rim FGA': Number,
    'At Rim FG%': Number,
    'At Rim Ast\'d': Number,
    'At Rim %Ast\'d': Number,
    '3 to <10 ft FG': Number,
    '3 to <10 ft FGA': Number,
    '3 to <10 ft FG%': Number,
    '3 to <10 ft Ast\'d': Number,
    '3 to <10 ft %Ast\'d': Number,
    '10 to <16 ft FG': Number,
    '10 to <16 ft FGA': Number,
    '10 to <16 ft FG%': Number,
    '10 to <16 ft Ast\'d': Number,
    '10 to <16 ft %Ast\'d': Number,
    '16 ft to <3-pt FG': Number,
    '16 ft to <3-pt FGA': Number,
    '16 ft to <3-pt FG%': Number,
    '16 ft to <3-pt Ast\'d': Number,
    '16 ft to <3-pt %Ast\'d': Number,
    '3-pt FG': Number,
    '3-pt FGA': Number,
    '3-pt FG%': Number,
    '3-pt Ast\'d': Number,
    '3-pt %Ast\'d': Number,
    'At Rim FGA%': Number,
    '3 to <10 ft FGA%': Number,
    '10 to <16 ft FGA%': Number,
    '16 ft to <3-pt FGA%': Number,
    '3-pt FGA%': Number,
    cluster_num: Number

});

module.exports = Player = mongoose.model('player', PlayerSchema);
